
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon May 16 08:55:50 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 38;
  public static final int CHAR = 49;
  public static final int CONST = 14;
  public static final int GE = 23;
  public static final int CASE = 35;
  public static final int CONTINUE = 44;
  public static final int LPAREN = 9;
  public static final int SEMI = 8;
  public static final int MINUS = 37;
  public static final int FOR = 17;
  public static final int RPAREN = 10;
  public static final int AND = 33;
  public static final int RECORD = 46;
  public static final int OR = 34;
  public static final int BOOL = 50;
  public static final int COMMA = 7;
  public static final int CLASS = 41;
  public static final int INC = 19;
  public static final int DIV = 29;
  public static final int GEQ = 25;
  public static final int PLUS = 5;
  public static final int IF = 15;
  public static final int DOT = 43;
  public static final int LE = 22;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int RBRACKET = 39;
  public static final int EQUAL = 6;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int ISEQUAL = 26;
  public static final int MUL = 28;
  public static final int NUMBER = 51;
  public static final int IDENT = 48;
  public static final int BREAK = 45;
  public static final int VOID = 13;
  public static final int SWITCH = 32;
  public static final int COL = 40;
  public static final int LBRACE = 11;
  public static final int ELSE = 16;
  public static final int READ = 31;
  public static final int GOTO = 30;
  public static final int WHILE = 18;
  public static final int NEQUAL = 27;
  public static final int RBRACE = 12;
  public static final int EXTENDS = 42;
  public static final int PROG = 2;
  public static final int LEQ = 24;
  public static final int DEC = 20;
  public static final int MODUL = 36;
  public static final int DO = 47;
  public static final int PRINT = 3;
}

